[build]
target = "thumbv6m-none-eabi"
target-dir = "build"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040 --log-format=oneline"
linker = "arm-none-eabi-gcc"
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tlink-rp.x",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
